# Generated by Django 4.2.18 on 2025-04-10 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'disabled'), (4, 'deleted')], default=1)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('unit_price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'disabled'), (4, 'deleted')], default=1)),
                ('quantity', models.IntegerField()),
                ('offer_price', models.FloatField()),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
